export class BluetoothConstants {
  //通用服务
  public static readonly NORMAL_SERVICE_UUID = 'F48A23C0-F69A-11E8-8EB2-F2801F1B9FD1';
  //通用服务发送数据特征值
  public static readonly NORMAL_SEND_UUID = 'F48A24C1-F69A-11E8-8EB2-F2801F1B9FD1'
  //通用服务接收数据特征值
  public static readonly NORMAL_RECEIVE_UUID = 'F48A25C2-F69A-11E8-8EB2-F2801F1B9FD1';
  //音频服务
  public static readonly AUDiO_SERVICE_UUID = 'E49A3001-F69A-11E8-8EB2-F2801F1B9FD1';
  //音频服务接收数据特征值
  public static readonly AUDIO_RECEIVE_UUID = 'E49A3003-F69A-11E8-8EB2-F2801F1B9FD1';
  // 2902一般用于notification或者indication
  public static readonly NOTIFY_DESC_UUID = '00002902-0000-1000-8000-00805F9B34FB';
}